const newBoard = () => {
  return {
    board: [
      [['x', 'redSquare', 'selectRed'],
        [null, 'blackSquare', ''],
        ['x', 'redSquare', 'selectRed'],
        [null, 'blackSquare', ''],
        ['x', 'redSquare', 'selectRed'],
        [null, 'blackSquare', ''],
        ['x', 'redSquare', 'selectRed'],
        [null, 'blackSquare', '']],

      [[null, 'blackSquare', ''],
        ['x', 'redSquare', 'selectRed'],
        [null, 'blackSquare', ''],
        ['x', 'redSquare', 'selectRed'],
        [null, 'blackSquare', ''],
        ['x', 'redSquare', 'selectRed'],
        [null, 'blackSquare', ''],
        ['x', 'redSquare', 'selectRed']],

      [['x', 'redSquare', 'selectRed'],
        [null, 'blackSquare', ''],
        ['x', 'redSquare', 'selectRed'],
        [null, 'blackSquare', ''],
        ['x', 'redSquare', 'selectRed'],
        [null, 'blackSquare', ''],
        ['x', 'redSquare', 'selectRed'],
        [null, 'blackSquare', '']],

      [[null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', '']],

      [[null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', '']],

      [[null, 'blackSquare', ''],
        ['o', 'redSquare', 'selectBlack'],
        [null, 'blackSquare', ''],
        ['o', 'redSquare', 'selectBlack'],
        [null, 'blackSquare', ''],
        ['o', 'redSquare', 'selectBlack'],
        [null, 'blackSquare', ''],
        ['o', 'redSquare', 'selectBlack']],

      [['o', 'redSquare', 'selectBlack'],
        [null, 'blackSquare', ''],
        ['o', 'redSquare', 'selectBlack'],
        [null, 'blackSquare', ''],
        ['o', 'redSquare', 'selectBlack'],
        [null, 'blackSquare', ''],
        ['o', 'redSquare', 'selectBlack'],
        [null, 'blackSquare', '']],

      [[null, 'blackSquare', ''],
        ['o', 'redSquare', 'selectBlack'],
        [null, 'blackSquare', ''],
        ['o', 'redSquare', 'selectBlack'],
        [null, 'blackSquare', ''],
        ['o', 'redSquare', 'selectBlack'],
        [null, 'blackSquare', ''],
        ['o', 'redSquare', 'selectBlack']],
    ],
    black: 12,
    red: 12,
    turn: 'black',
    autoJumpRed: false,
    autoJumpBlack: false
  }
};

const testBoard = () => {
  return {
    board: [
      [[null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', '']],

      [[null, 'blackSquare', ''],
        ['o', 'redSquare', 'selectBlack'],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', '']],

      [[null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', '']],

      [[null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', '']],

      [[null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        ['x', 'redSquare', 'selectRed'],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', '']],

      [[null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        ['o', 'redSquare', 'selectBlack'],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', '']],

      [[null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        ['x', 'redSquare', 'selectRed'],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', '']],

      [[null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', ''],
        [null, 'blackSquare', ''],
        [null, 'redSquare', '']],
    ],
    black: 2,
    red: 2,
    turn: 'black',
    autoJumpRed: false,
    autoJumpBlack: true,
    playerOne: 'Test One',
    playerTwo: 'Test Two',
  };
};

export default { newBoard, testBoard };